### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by bowbahdoe** [helpermethod/zip-forge#41]
Would allow this to be used with jlink.

**Comment by helpermethod** [comment]
Hi @bowbahdoe!

I've added an Automatic Module Name to the JAR, so it should already be usable with jlink. If we need a module.info, I'd have to raise the language level to at least 9.

https://github.com/helpermethod/zip-forge/blob/main/pom.xml#L214

**Comment by bowbahdoe** [comment]
JLink does not allow automatic modules to be used, even with an Automatic Module Name is in the jar.

![demo](https://github.com/helpermethod/zip-forge/assets/5004262/70acb786-eb20-42f3-9e2b-01d5a16215a1)

You should be able to add a module-info with [moditect](https://github.com/moditect/moditect#adding-a-module-descriptor-to-the-project-jar) without bumping the version for the rest of the project.

**Comment by helpermethod** [comment]
Hi @bowbahdoe!

I wasn't aware of this limitation. I guess it's best to use moditect like you suggested.

**Comment by helpermethod** [comment]
Hi @bowbahdoe,

I'll release a new jlink-compatible version this evening.

**Comment by bowbahdoe** [comment]
Thank you!
